databases:
  - name: quiz-db
    plan: free

services:
  - type: redis
    name: quiz-redis
    plan: free
    ipAllowList: []

  - type: web
    name: quiz-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "daphne GameQuiz.asgi:application -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase: {name: quiz-db, property: connectionString}
      - key: REDIS_URL
        fromService: {type: redis, name: quiz-redis, property: connectionString}
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"