# Generated by Django 5.2.8 on 2026-04-24 14:03

import django.db.models.deletion
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('wait', 'Waiting'), ('play', 'Playing'), ('finish', 'Finished')], default='wait', max_length=10)),
                ('current_question_index', models.IntegerField(default=-1)),
                ('current_question_id', models.PositiveIntegerField(blank=True, null=True)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('question_revealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('avatar', models.CharField(default='🦊', max_length=10)),
                ('exp', models.IntegerField(default=0)),
                ('is_host', models.BooleanField(default=False)),
                ('last_answer', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(default=quiz.models.generate_player_token, max_length=64, unique=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz.lobby')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_host', True)), fields=('lobby',), name='one_host_per_lobby')],
            },
        ),
    ]
